### ISSUE TITLE
Switching between VOD flavors doesn't match the correct flavor

### ISSUE THREAD

**Issue by jabakirCsaba** [kaltura/mwEmbed#1587]
Hey,
The VOD entry I am playing in the HTML5 player has 5 flavors with different bitrates. 

![image](https://cloud.githubusercontent.com/assets/3157952/6506005/b9a57288-c347-11e4-870a-367c64fed485.png)

SInce the transcoding profile has heights matching for 360p and 720p, the player shows HQ or without HQ. Allso the player has the source selector simple format selected. 

![image](https://cloud.githubusercontent.com/assets/3157952/6506061/139f3ef4-c348-11e4-95fc-e36dc48675d1.png)

When the playback starts, the playManifest response shows 3 elements for the media. By selecting any flavors from the source selector, it starts switching, and when finishes switching, the fragments loaded doesn't match the selected size/bitrate.

Also: the flavor selector has more items showing than what is in the manifest. 

![image](https://cloud.githubusercontent.com/assets/3157952/6505914/fe39c026-c346-11e4-964e-d24ce877b1c3.png)

![image](https://cloud.githubusercontent.com/assets/3157952/6505978/7fd0c7d8-c347-11e4-9e34-2c35609bc00f.png)

Thanks 
Csaba

**Comment by AquileaSFX** [comment]
Hello,

also when using LIVE,
and the flavor selector is activated
if you click the high quality flavor
the player will play the lower

and if you click the lower
it will play the better quality one.

**Comment by OrenMe** [comment]
The player only loads the manifest file containing the manifest renditions when play button is pressed.
Due to the logic of sourceSelector back than the player was showing the progressive flavours before play was initiated so it exhibited different flavours before and after playback started.
The player will now only show progressive bitrates if it will play progressive, and will show the manifest flavours if it plays HLS/DASH
