### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by paladox** [kaltura/mwEmbed#1897]
Hi please update your README file with updated information like updated links since some do not work like your release notes. and please example how to create the skin or other things that use to be included in v1.

**Comment by kaltura-hooks** [comment]
Hi @paladox,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by paladox** [comment]
Hi I use timedmediahandler for mediawiki and they use a very old version of kaulter player. They were thinking off upgrading but with all the changes in the core it would not be worth it and it since it doesent include any default skin now. They now testing usage of video-js which is light weight but code updated to match js and easly be able to update. They now consider defunct in timedmediahandler so readme needs to be updated to support creating a skin or at least include a default skin like you did in v1 but allow it to be easly customise. Include information on upgrading from v1 to v2. and other updated information please. This is not an issue this is a feature request.

**Comment by jessp01** [comment]
Hello,

As far as the release notes go:
https://github.com/kaltura/mwEmbed#release-notes
seems to point to the correct location, what link for broken for you?

I will ask the relevant devs for instructions about the skins.

Thanks,

**Comment by jessp01** [comment]
A guide for skins can be found here:
http://knowledge.kaltura.com/kaltura-player-toolkit-theme-skin-and-plugins-guide#player+skin

**Comment by jessp01** [comment]
Closing due to lack of feedback, if you still have an issue with the release notes, please reopen.
