### ISSUE TITLE
Controls Hovering is lost when changing media

### ISSUE THREAD

**Issue by oferch** [kaltura/mwEmbed#1917]
Hi,

I have a simple html5 player based on v.2.30.2.
The player is configured to have hovering controls, ans basically works fine.
But, if I load the player empty, and in the kdpEmpty listener loads an entry the controls remains in block mode. 

function jsCallbackReady(playerId) {
    var kdp = document.getElementById( playerId );
      kdp.kBind("kdpEmpty", function( data, id ){
    console.log("kWidget player empty: " + document.getElementById(playerId).localName);
        kdp.sendNotification("changeMedia", {
            "entryId": "0_kp7xtxfe"
        });
    });
}

kWidget.embed({
  "targetId": "kaltura_player_1435050847",
  "wid": "_102",
  "uiconf_id": 11601492,
  "flashvars": {
    "streamerType": "auto"
  },
  "cache_st": 1435050847,
  "entry_id": ""
});

**Comment by kaltura-hooks** [comment]
Hi @oferch,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Working -tested with v2.60.2
