### ISSUE TITLE
Force flash via Kwidget embed

### ISSUE THREAD

**Issue by oferch** [kaltura/mwEmbed#1997]
Hi,

This is more a question, not an issue.
I'm using ver 2.30.2 of the lib.
How Can I use the kwidget embed and still force it to load Flash player (when I need, currently I want desktop to be flash), I tried all flags that I know and it still loads the HTML5 version.

Ofer

**Comment by kaltura-hooks** [comment]
Hi @oferch,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amirch1** [comment]
Hi Ofer,
You should set the Flashvar EmbedPlayer.ForceKPlayer to true. You can do this in the player UIConf level or, before your embed call, add: mw.setConfig( 'EmbedPlayer.ForceKPlayer' , true );
The player interface is always HTML5 based (in V2 players) - however, setting this Flashvar will cause the video to be played in a chromeless Flash layer which supports all Flash video formats.

Amir

**Comment by oferch** [comment]
Hi Amir,
The sample below is of a ui conf created with the universal studio, and it plays HTML5 video tag even with the flag (unless I misunderstand something)
http://www.whitenblue.com/kaltura/flash.html

**Comment by amirch1** [comment]
Hi Ofer,
As I said, the interface is always HTML5 in our V2 players. The video itself is played using our chromeless Flash player (see attached screen shot).
![screen shot 2015-07-28 at 10 40 06 am](https://cloud.githubusercontent.com/assets/3839950/8926030/34884eb4-3515-11e5-98ee-3d30732fb8ca.png)

**Comment by oferch** [comment]
Thanks. I see that now.

Ofer
