### ISSUE TITLE
EmbedPlayer.WebKitPlaysInline is not working

### ISSUE THREAD

**Issue by RobertBoes** [kaltura/mwEmbed#2041]
I have tried a lot of different options, none of them are setting webkit-playsinline on the video object.
What i have tried:
``` js
"flashvars": {
   "EmbedPlayer.WebKitPlaysInline": true
}
```

``` js
"flashvars": {
   "EmbedPlayer": {
     "WebKitPlaysInline": true
   }
}
```

And so on, almost any combination.. Why is this not working?

**Comment by kaltura-hooks** [comment]
Hi @RobertBoes,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amirch1** [comment]
@RobertBoes - setting the flashvar 'EmbedPlayer.WebKitPlaysInline': true should work. 
Please try using a code like this and you will see the 'webkit-playsinline' attribute on the video object.
Once verified, please close pull request https://github.com/kaltura/mwEmbed/pull/2053.
```
<!DOCTYPE HTML>
<html>
<head>
</head>
<body>
<script src="http://cdnapi.kaltura.com/p/1645161/sp/164516100/embedIframeJs/uiconf_id/30591871/partner_id/1645161"></script>
<div id="kaltura_player_1443080692" style="width: 560px; height: 395px;" itemprop="video" itemscope itemtype="http://schema.org/VideoObject"></div>
<script>
    kWidget.embed({
        "targetId": "kaltura_player_1443080692",
        "wid": "_1645161",
        "uiconf_id": 30591871,
        "flashvars": {
            "EmbedPlayer.WebKitPlaysInline": true
        },
        "cache_st": 1443080692,
        "entry_id": "1_gph0mg3z"
    });
</script></body>
</html>
```

**Comment by RobertBoes** [comment]
Hi @amirch1 

Currently we are using the embedIframeJs v2.27.1. At the time this was the current version, but the docs stated that WebKitPlaysInline could be set. I will update our player to confirm if v2.33 works correctly and I will update this post to let you know

**Comment by itaykinnrot** [comment]
Great!
