### ISSUE TITLE
After change media playerPlayEnd

### ISSUE THREAD

**Issue by faiverson** [kaltura/mwEmbed#2201]
I'm changing the media entry on the event 'playerPlayEnd' and sending the notification 'doPlay' after the entry has changed, once the entry has been changed the event 'playerPlayEnd' is not fired anymore.
The others like 'playerUpdatePlayhead' are working but playerPlayEnd doens't.

**Comment by faiverson** [comment]
Example code:
````
kdp.kBind('playerPlayEnd', function(){
	console.log('playerPlayEnd', kdp);
        document.getElementById(self.$player.attr('id')).sendNotification("changeMedia", {'entryId': '0_uyevskzf'});
       document.getElementById(self.$player.attr('id')).sendNotification('doPlay');
});
````

**Comment by kaltura-hooks** [comment]
Hi @faiverson,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by faiverson** [comment]
Tested on chrome  45.0.2454.101 on a mac yosemite
I'm using the cdn like this: 
'http://cdnapi.kaltura.com/p/' + partnerId + '/sp/' + partnerId + '00/embedIframeJs/uiconf_id/' + uiConfigId + '/partner_id/' + partnerId;
And then embeding the player with kWidget.embed
Like this example (http://player.kaltura.com/docs/index.php?path=kwidget)

**Comment by itaykinnrot** [comment]
You can use autoplay flag in order to resolve it.
you should wait for playerReady before send doPlay

**Comment by faiverson** [comment]
Thank you! That solve the problem yes!

**Comment by faiverson** [comment]
So for the record the issue here is that I'm using doPlay notification after change a media, and that reset the player. If the flag autoplay is set as false, I should wait to the event playerReady to send doPlay notification
