### ISSUE TITLE
Chrome won't autoplay for videos under 340px

### ISSUE THREAD

**Issue by KLVTZ** [kaltura/mwEmbed#2211]
Problem
-----------
We are noticing that chrome will not autoplay for videos under 340px. Instead, the resource will default to what appears to be the flash player:

![screen shot 2015-10-06 at 2 48 29 pm](https://cloud.githubusercontent.com/assets/3615935/10323879/d6ea9746-6c3a-11e5-83df-7a25f87b5883.png)

Discussion
---------------
Autoplay does work in the following scenarios:
- Go to `chrome://plugins` and disable `Adobe Flash Player - Version: 19.0.0.185`, autoplay works. 
- Use another popular browser (i..e firefox, safari etc), autoplay works. 
- Increase the unique video container tag to a height greater than 340px, autoplay works.

Upping the height does indeed solve the problem but this does not explain why chrome reverts to flash when this occurs. We would ideally want to keep the height. This problem exists on a few sites we manage that have a very small height.

Specs
--------
- Google Chrome: Version 45.0.2454.101 (64-bit)

Embed Resource
------------------------

Video wrapper defines a current height of `213px`. The target id is set to a width and height of `100%`

```
<div class="video-wrapper">
    <div id="entry-video"></div>
</div>
```

- kWidget: Kaltura HTML5 Version: 2.35
```
<script>
kWidget.embed({
    'targetId': 'entry-video',
    'wid': '_1807801',
    'uiconf_id': '28719962',
    'entry_id': '0_cpyr6cps',
    'flashvars': {'autoPlay': true, 'autoMute': false}
});
</script>
```

**Comment by kaltura-hooks** [comment]
Hi @KLVTZ,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by dyonehara** [comment]
Could this possibly be due to the recent change in Chrome that detects blocks any flash advertisements/pre-rolls?

https://plus.google.com/+GoogleAds/posts/2PmwKinJ7nj

**Comment by itaykinnrot** [comment]
Yes - Chrome added a rule that flash object that looks like ads and not like main video will need user click in order to play.
Not sure what is the player configuration but you could use html5 playback as default or make the player bigger.
Thanks,

**Comment by jmhm** [comment]
Is there any other way to force Kaltura to not try with Flash at all, I keep seeing the same problem cited here. I'm using:  mw.setConfig( 'KalturaSupport.LeadWithHTML5', true );

And on some players, I need the player to be small, is just the way it is. Is there any other work around?

Thanks
