### ISSUE TITLE
Question? Embed player in FB 

### ISSUE THREAD

**Issue by elranu** [kaltura/mwEmbed#2250]
Hi,
     I'm being reading your code to understand how did you could accomplish to embed a iframe player on a FB post. And I could not find nothing. The only thing I found was: 
https://github.com/kaltura/mwEmbed/blob/b2b1bd03ea25d956727fef07f1c88c4aa5708a33/modules/KalturaSupport/kalturaIframeClass.php#L402

But It did not work for me either. Can you tell me your trick? Why you could embed your player in a FB post? I wrote the question here:http://stackoverflow.com/questions/33215828/how-to-embed-a-iframe-player-in-fbs-wall

I will be really grateful if you answer me :)

Regards,
Mariano

**Comment by kaltura-hooks** [comment]
Hi @elranu,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
Hi @elranu,
In order to iframe embed at facebook you need to whitelist the player domain.
If you'll use Kaltura cloud player - you'll get it.

Thanks,

**Comment by Jrubensson** [comment]
Bringing this back up. How do I apply for a whitelist of my domain?
