### ISSUE TITLE
VAST flash ads not playing

### ISSUE THREAD

**Issue by kjt1212** [kaltura/mwEmbed#2275]
Hi, I am trying to inject a preroll ad in my video. I tried the link http://player.kaltura.com/docs/index.php?path=kvast however, when I try to see its demo the ad does not play at all. The video plays directly. I did not make any changes to the preroll url am just trying to run the demo as is. What could be the issue?

**Comment by kaltura-hooks** [comment]
Hi @kjt1212,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kjt1212** [comment]
Hi, thanks for your response. I agree this is a general question. However, there is a similar issue logged for VAST ads on this repository and a representation responded to it and the issue is now closed. I tried the link the representative mentioned in the comment. Heres the issue link - https://github.com/kaltura/mwEmbed/issues/360. Thats why I thought of raising an issue here itself. Do you believe the forum would be a better option?

**Comment by itaykinnrot** [comment]
can you add the ad tag url?
