### ISSUE TITLE
Using HTTPS for cdnapi.kaltura.com gives an insecure response

### ISSUE THREAD

**Issue by KLVTZ** [kaltura/mwEmbed#2303]
Problem
------------
>  `GET https://cdnapi.kaltura.com/p/123/sp/123/embedIframeJs/uiconf_id/123/parner_id/123`

When requesting the above URL over HTTPS, we receive a `net::ERR_INSECURE_RESPONSE`.

Discussion
---------------
When looking at the request itself, it appears your CDN is in fact Akamai. More specifically, it seems your security certificate isn't valid with `a248.e.akamai.net` over HTTPS. 

Is there a secure CDN URL we can use instead? Or can we work on getting akamai setup to use HTTPS? 

Thanks!

**Comment by itaykinnrot** [comment]
Use cdnapisec

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Nov 17, 2015 at 9:53 PM -0800, "Justin Page" <notifications@github.com<mailto:notifications@github.com>> wrote:

Problem

GET https://cdnapi.kaltura.com/p/123/sp/123/embedIframeJs/uiconf_id/123/parner_id/123

When requesting the above URL over HTTPS, we receive a net::ERR_INSECURE_RESPONSE.

Discussion

When looking at the request itself, it appears your CDN is in fact Akamai. More specifically, it seems your security certificate isn't valid with a248.e.akamai.net over HTTPS.

Is there a secure CDN URL we can use instead? Or can we work on getting akamai setup to use HTTPS?

Thanks!

-

**Comment by kaltura-hooks** [comment]
Hi @KLVTZ,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by KLVTZ** [comment]
@itaykinnrot thank you! Is it possible we could specify this in documentation? Unless there is an entry that already exists?
