### ISSUE TITLE
player upgrade from v2.37.1 to v2.38.3 breaks responsive resizing

### ISSUE THREAD

**Issue by kmcculloch** [kaltura/mwEmbed#2431]
We cloned a v2.37.1 player in the KMC in order to test a new setting. The cloned player was automatically upgraded to v2.38.3. We noticed that the inside elements of the video iframe were no longer maintaining their aspect ratio when we manually changed our browser width. (See screenshot.) We used the player version utility to downgrade our clone from v2.38.3 to v2.37.1 and the regression went away.

![](https://s3.amazonaws.com/uploads.hipchat.com/497261/3297459/MF9G1877HuOZx0o/Screen%20Shot%202016-01-04%20at%2012.07.07%20PM.png)

**Comment by kaltura-hooks** [comment]
Hi @kmcculloch,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
If still valid with our latest version(v2.65) please comment - thanks,
