### ISSUE TITLE
kWidget.embed Chromecast plugin. Only first video from playlist plays on chromecast

### ISSUE THREAD

**Issue by danil-farafontov** [kaltura/mwEmbed#2460]
I'm trying to integrate chromecast suport into Kaltura Playlist Player.
Seems everything works fine for first video being played.
But when you select another video from playlist or when Player automaticaly start playing next video it stops from casting to chromecast device.

Actually I'm not sure if this plugin was designed to work with playlist.

Here is how I embed player onto my web page:

```
kWidget.embed({
            "targetId": "kalturaPlayer",
            "wid": "_102",
            "uiconf_id": 23448209,
            "flashvars": {
                "streamerType": "auto",
                "playlistAPI.kpl0Id": kalturaPlaylistId
            },
            "cache_st": 1453356055
        });
```

I have used this line to import plugin in studio:
`chromecast.plugin=true&chromecast.applicationID=FFCC6D19&chromecast.debugReceiver=false&chromecast.receiverLogo=true&chromecast.useKalturaPlayer=true&chromecast.debugKalturaPlayer=false&inlineScript=false`

I see next in my Chrome console when second video starting to play:
`Uncaught TypeError: Cannot read property 'src' of null`
`Chromecast: Error. code: session_error, description: INVALID_MEDIA_SESSION_ID`
`Uncaught TypeError: this.embedPlayer.updatePlayhead is not a function`

Is it bug?
Or maybe I miss something in configuration of player in kmc studio?
Is this plugin was designed to work with playlist?

Thanks in advance for any help.

Regards, Danil.

**Comment by kaltura-hooks** [comment]
Hi @danil-farafontov,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by danil-farafontov** [comment]
I'm using self-hosted rpm install on Centos 6.5.

```
rpm -qa "kaltura*"
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-html5-studio-v2.0.2-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-red5-1.0.6-1.x86_64
kaltura-release-11.5.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-base-11.5.0-7.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kmc-v5.39.11-6.noarch
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-dwh-9.5.0-2.noarch
kaltura-monit-5.13-1.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-html5lib-v2.38.1-1.noarch
kaltura-nginx-1.8.0-9.x86_64
kaltura-front-11.5.0-1.noarch
kaltura-server-11.6.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-postinst-1.0.30-10.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.5.0-1.noarch
kaltura-libmcrypt-2.5.7-5.x86_64
```

```
mysql --version
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
```

It's single all in 1 server

I do not see any errors in log when repeat this bug.

**Comment by danil-farafontov** [comment]
Here is how my Playlist Player looks like when first video playing.
![chromecastpluginbug1](https://cloud.githubusercontent.com/assets/2087320/12549339/7b1d1574-c37e-11e5-87cb-3fd6cf7c5232.png)

Here is how my Playlist Player looks like when second video playing. It stops casting to chromecast device and start playing in browser. But it still display watermark "Now playing on chromecast..."
![chromecastpluginbug2](https://cloud.githubusercontent.com/assets/2087320/12549343/7ef86586-c37e-11e5-96a3-945d6eca6dbb.png)

**Comment by amirch1** [comment]
Hi,
Currently our Chromecast implementation do not support playlists. I will check with our product team regarding this, and update when this feature is going to be available.

**Comment by danil-farafontov** [comment]
Hello Amir,
Thank you for your answer.
Looking forward to hear back from you regarding when we can wait update of plugin for support playlists.

**Comment by OrenMe** [comment]
@danil-farafontov the kaltura chromecast supports playlists. you can try with latest version. thanks.
