### ISSUE TITLE
Can I handle events of player in Chromecast plugin?

### ISSUE THREAD

**Issue by killmeswifty** [kaltura/mwEmbed#2470]
Hello, 
I need to extend chromecast plugin functional. Can I somehow handle events of kaltura player/kdp(not embedPlayer) from chromecast.js? (/opt/kaltura/web/html5/html5lib/v2.38.1/modules/Chromecast/resources/chromecast.js). How can I access kaltura player object for handle playlist events? like
http://player.kaltura.com/docs/api#relatedVideoSelect

**Comment by kaltura-hooks** [comment]
Hi @killmeswifty,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by killmeswifty** [comment]
I'm using self-hosted rpm install on Centos 6.5.

```
rpm -qa "kaltura*"
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-html5-studio-v2.0.2-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-red5-1.0.6-1.x86_64
kaltura-release-11.5.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-pentaho-4.2.1-2.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-base-11.5.0-7.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kmc-v5.39.11-6.noarch
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-dwh-9.5.0-2.noarch
kaltura-monit-5.13-1.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-html5lib-v2.38.1-1.noarch
kaltura-nginx-1.8.0-9.x86_64
kaltura-front-11.5.0-1.noarch
kaltura-server-11.6.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-postinst-1.0.30-10.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-batch-11.5.0-1.noarch
kaltura-libmcrypt-2.5.7-5.x86_64
mysql --version
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
```
It's single all in 1 server

**Comment by amirch1** [comment]
@killmeswifty - you can access all player events from the Chromecast plugin. These are the embedPlayer events. Please let us know what you are trying to achieve so we can provide the best practices. Note that our Chromecast implementation currently do not support playlists so adding a playlist functionality is currently not possible.

**Comment by OrenMe** [comment]
@killmeswifty closing. please reopen or open a new issue if you have additional questions.
