### ISSUE TITLE
IE9 Get wrong font face if icomoon.svg is defined in the fonts folder

### ISSUE THREAD

**Issue by chriswu14** [kaltura/mwEmbed#2480]
`@font-face {
font-family: 'icomoon';
    src: url(http://cdnapi.kaltura.com/html5/html5lib/v2.33//skins/kdark/css/../fonts/icomoon.eot?2015-07-23T14:10:00Z);
    src: url(http://cdnapi.kaltura.com/html5/html5lib/v2.33//skins/kdark/css/../fonts/icomoon.eot?2015-07-23T14:10:00Z&#iefix) format('embedded-opentype'), url(http://cdnapi.kaltura.com/html5/html5lib/v2.33//skins/kdark/css/../fonts/icomoon.woff?2015-07-23T14:10:00Z) format('woff'), url(http://cdnapi.kaltura.com/html5/html5lib/v2.33//skins/kdark/css/../fonts/icomoon.ttf?2015-07-23T14:10:00Z) format('truetype'), url('../fonts/icomoon.svg#icomoon') format('svg');
    font-weight: normal;
    font-style: normal
}`

I have been knocking my head to the wall trying to figure out why the hell only IE9 try to use my own set of icomoon icons. It turned out the last src url I get from minified css was not appending any cdn so I guess it is looking into my css files.

I hope my assumption is correct will verify tomorrow and update here.

**Comment by kaltura-hooks** [comment]
Hi @chriswu14,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by chriswu14** [comment]
I figured out. the @font-face is overwritten by our icomoon setting

**Comment by itaykinnrot** [comment]
Great - Closing
