### ISSUE TITLE
How to get dash working

### ISSUE THREAD

**Issue by Patryk57** [kaltura/mwEmbed#2485]
Dear Kaltura Community,

I am currently struggeling to get Kaltura to play MPEG-DASH.
That is why I am humbly asking for your help.

To do so, We installed Kaltura-Nginx to delivery our VOD content in Dash. This part works just great.

Here are what we achieved:
1. On kaltura side, we have created a dedicated Delivery profile.
2. We make sure that we convert our medias to a flavor compatible with dash ( with the "dash" tag).
3. While previewing a media, we enforce the streamType to mpegdash.
The player is well receiving the manifest.mpd playlist generated on the fly by nginx.
ERROR: But instead of playing the media, the player returns the following error:

> An error was experienced when playing the video. Please check your internet connection and try again.

We have of course no internet issue and NGINX is well delivering the manifest, which we can play with another Dash player), which makes me say that there is still something to do/configure on the player side.

Do you have any hint on where I should look at?
We tried to implement the _dasheverywhere _ plugin without success.

Here are some info about my configuration:
We use a split infrastructure ( our Staging is composed of 1 front, 2 batches, 1 SQL and a NAS server)

**Installed packages ( RPM - CentOS)** We did an update the our previous version to get v 11.5

> kaltura-kmc-v5.39.11-6.noarch`
kaltura-nginx-1.8.0-12.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-html5lib-v2.38.1-1.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-postinst-1.0.30-10.noarch
kaltura-monit-5.13-1.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-fdk-acc-0.1.3-1.x86_64
kaltura-kcw-1.0.0-6.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-kdp3-v3.9.9-2.noarch
kaltura-base-11.5.0-7.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-libmemcached-1.0.16-2.x86_64
kaltura-ksr-v1.0.44-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-front-11.5.0-1.noarch
kaltura-release-11.5.0-1.noarch
kaltura-server-11.5.0-1.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-red5-1.0.6-1.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-html5-studio-v2.0.2-1.noarch
kaltura-batch-11.5.0-1.noarch
kaltura-dwh-9.5.0-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-kdpwrapper-v11.0-1.noarch

We tried the following HTML5 players:
> v2.37.3
v2.38.1
v2.38.3
v2.39.1
v2.40.2

There is really not much in the logs regarding my issue:

> --
2016-02-03 18:05:15 [0.000695] [146.220.130.51] [1723866251] [28] [PS2] [sfView->initialize] INFO: {sfView} initialize view for "extwidget/preview"
2016-02-03 18:05:15 [0.000596] [146.220.130.51] [1723866251] [29] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/modules/extwidget/templates/previewSuccess.php"
2016-02-03 18:05:15 [0.000762] [146.220.130.51] [1723866251] [30] [PS2] [sfRenderingFilter->execute] INFO: {sfFilter} render to client

Do you have any idea where I should look at in order to debug this?

Many thanks in advance for helping me.

--

Patrick

**Comment by kaltura-hooks** [comment]
Hi @Patryk57,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by oferch** [comment]
Any success with making it play?

**Comment by OrenMe** [comment]
@oferch the player fully supports DASH playback.
You need to enable the dash plugin in order to get dash playback.

**Comment by oferch** [comment]
@OrenMe  Since which version?
Also is it live streaming only, or any clip?

**Comment by OrenMe** [comment]
It has been supported for a few versions now for encrypted content.
A new version coming out tomorrow, v2.48, will support clear contact as well.
Currently support clip, live support should be introduced on coming version (2.49 or 2.50).

**Comment by jessp01** [comment]
Closing this one as 2.48.1 is the current stable and is available in the official repos.
