### ISSUE TITLE
HMTL5 OGV 

### ISSUE THREAD

**Issue by flood1234** [kaltura/mwEmbed#2576]
Hi, 

Looking at exporting movies in HTML5 video formats. Is there any good software recommendations for this purpose? Require the following formats:

MP4/H.264 (not a problem)
WebM (This could be an option: http://www.sorensonmedia.com/squeeze/squeeze-desktop/ )
Ogg (is this just audio?) (or OGV?) - .oggtherora.ogv - Squeeze software above doesn't cover.

Adobe doesn't seem to natively export to HTML5 video formats without unofficial scripts, and free software such as http://www.mirovideoconverter.com/ have limited settings. Willing to pay for software, but just want to know if there's an option that would cover all of the above, is fairly robust, has some quality settings and is used widely in industry?

Thanks.

**Comment by kaltura-hooks** [comment]
Hi @flood1234,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @flood1234, this is not an encoding support forum.
I can advice on FFMPEG but any supporting SW will do.
