### ISSUE TITLE
EmbedPlayer.WebKitPlaysInline doesn't works

### ISSUE THREAD

**Issue by peterrei** [kaltura/mwEmbed#2755]
the UIvar EmbedPlayer.WebKitPlaysInline doesn't works, the video player on webkit persists to open/play the video (ad and content) just in full screen and not inline.
I tested on v2.39 and v2.43 with iPhone 6s device and iOS 9.3

**Comment by kaltura-hooks** [comment]
Hi @peterrei,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by peterrei** [comment]
- I tested with Safari mobile browser on iPhone 6s with iOS 9.3
- I tested with 2 Kaltura installation:
    - Kaltura Self Hosted, deployed in cluster via RPM (Community Edition 11.7.0)
    - Kaltura Self Hosted deployed on Single Server via RPM (Community Edition 11.14.0)
- List of installed RPMs:
    - 11.7.0 cluster:
`kaltura-html5-studio-v2.0.2-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-server-11.7.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-nginx-1.8.0-12.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-postinst-1.0.30-14.noarch
kaltura-html5lib-v2.39-1.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-front-11.7.0-1.noarch
kaltura-release-11.8.0-1.noarch
kaltura-lame-3.99.5-3.x86_64
kaltura-segmenter-1.0-2.x86_64
kaltura-libfaac-1.26-1.x86_64
kaltura-base-11.7.0-10.noarch
kaltura-krecord-1.0.0-1.noarch
kaltura-kmc-v5.40.1-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-sphinx-2.2.1-17.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-clipapp-1.3-2.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-dwh-11.3.0-1.noarch
kaltura-batch-11.7.0-1.noarch`

    - 11.14.0 single server:
`kaltura-clipapp-1.3-2.noarch
kaltura-kupload-1.0.0-1.noarch
kaltura-mencoder-3.4.6-9.x86_64
kaltura-base-11.14.0-8.noarch
kaltura-html5lib-v2.43-1.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-a52dec-0.7.4-11.x86_64
kaltura-monit-5.13-1.x86_64
kaltura-sphinx-2.2.1-17.x86_64
kaltura-release-11.14.0-1.noarch
kaltura-libopencore-amr-0.1.2-2.x86_64
kaltura-lame-3.99.5-3.x86_64
kaltura-ffmpeg-2.7.2-2.x86_64
kaltura-libmcrypt-2.5.7-5.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-kdp-v2.7.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-libfaac-1.26-1.x86_64
kaltura-librtmp-2.3-2.x86_64
kaltura-dwh-11.3.0-1.noarch
kaltura-html5-studio-v2.0.5-1.noarch
kaltura-batch-11.14.0-1.noarch
kaltura-nginx-1.8.1-5.x86_64
kaltura-kmc-v5.40.2-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-segmenter-1.0-2.x86_64
kaltura-pentaho-4.2.1-2.x86_64
kaltura-postinst-1.0.31-7.noarch
kaltura-front-11.14.0-1.noarch
kaltura-server-11.14.0-1.noarch
kaltura-libass-0.9.11-2.x86_64
kaltura-ffmpeg-aux-2.1.3-1.x86_64
kaltura-libmcrypt-devel-2.5.7-5.x86_64
kaltura-krecord-1.0.0-1.noarch`

    - Both installation are configured on centos 6.7 and mySQL 5.1
    - this the output for command tail -f ... from single server (I can't share in public the log of production platform):
2016-05-13 17:15:53 [0.000063] [2094523316] [7] [BATCH] [KalturaClientBase->doCurl] NOTICE: post: {"format":"3","ignoreNull":true,"clientTag":"batch: kaltura.local KScheduleHelper index: 0 sessionId: 2094523316","apiVersion":"3.3.0","partnerId":"-1","ks":"[omitted]","kalsig":"4b1c2d04ba7478f8d1009085f5359295"}
2016-05-13 17:15:53 [0.010674] [2094523316] [8] [BATCH] [KScheduleHelper->run] ERR: exception 'Exception' with message 'System is not yet ready - ping failed' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/batch/batches/KScheduleHelper.class.php(42): KalturaLog::err('System is not y...')

**Comment by OrenMe** [comment]
Ho @peterrei webkit playsinline is supported by apple from iOS10 only.
