### ISSUE TITLE
this.getPath() and this.getKalturaThumbUrl() Error

### ISSUE THREAD

**Issue by arunshan** [kaltura/mwEmbed#2764]
For some reason the kaltura player does not work here:

https://fuisz-experience-staging.herokuapp.com/573b8914d2e9531a5704fcb8/

But it works from `http://localhost:3000`. Do I have to whitelist any domain ? Please let me know.

<img width="668" alt="image 2016-05-17 at 2 14 25 pm" src="https://cloud.githubusercontent.com/assets/1124102/15339563/e5e7d8e4-1c39-11e6-91b2-3872827ac612.png">

**Comment by kaltura-hooks** [comment]
Hi @arunshan,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @arunshan,
Sorry for the delay in response. The URL you posted is no longer valid. If you still have this issue, can you post a new link so we can look?
Thanks,

**Comment by arunshan** [comment]
Hi Jess, I got our experiences working using Kaltura player. Thank you for
getting back though.

Thank You
Arun

**Comment by jessp01** [comment]
Most welcome && glad we're good.
