### ISSUE TITLE
hls stream switch to progresive download on MAC Safari 

### ISSUE THREAD

**Issue by slash851** [kaltura/mwEmbed#2781]
When opening video on MAC Safari it plays HLS and it downloads .ts chunks - correct behavior
But when manually selecting another bitrate on sourceSelector it start playing .mp4 progresive dowlnoad.

Test players below. Both old 36 and newer 42 versions do the same

http://kmc.kaltura.com/html5/html5lib/v2.42/modules/KalturaSupport/tests/SourceSwitchingEvents.qunit.html

http://kmc.kaltura.com/html5/html5lib/v2.36/modules/KalturaSupport/tests/SourceSwitchingEvents.qunit.html

**Comment by kaltura-hooks** [comment]
Hi @slash851,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @slash851,

Apple doesn't allow manual bitrate selection.
In order to give this ability to our users we emulate this by loading automatically the HLS stream on Safari, which will enable seamless ABR switching by the Safari browser player.
If a user wants to control the bitrate for any reason he can switch it manually, but this can only be done if we set the playback to a progressive single bitrate stream.
If you don't require such functionality you can disable the sourceSelector plugin on Safari.
