### ISSUE TITLE
Unable to use chaptersEdit Plugin

### ISSUE THREAD

**Issue by prakashsaraf** [kaltura/mwEmbed#2928]
Hi, I am new to Kaltura and trying to use the chaptersEdit plugin. 
I followed the steps for using dynamic embed and my test HTML looks like (attached)-
[kaltura_chapteredit.docx](https://github.com/kaltura/mwEmbed/files/402999/kaltura_chapteredit.docx)

My video is getting played but I do not see the chapter edit div being filled up.
I am not even seeing any error on any console.

Can someone please help if am missing anything?

**Comment by kaltura-hooks** [comment]
Hi @prakashsaraf,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by prakashsaraf** [comment]
Hi, I think I got the rootcause of this issue.
The problem is if I am using the URL like 
http://kaltura/p/100/sp/10000/embedIframeJs/uiconf_id/23448368/partner_id/100
to load the embedLoader -> It marks the player 23448368 as config loaded viz - 
kWidget.uiConfScriptLoadList['23448368'] = 1

Due to this the dynamic parameter when added via embed call do not give a call to service uiConfJs and the plugin is not loaded.

If I mark kWidget.uiConfScriptLoadList['23448368'] as null before calling embed, I get the plugin working.

Not sure, but is this an issue?

**Comment by OrenMe** [comment]
Hi @prakashsaraf, the on page chapters plugin is not supported anymore.
You can use the new chapters plugin with the editor via KMS.
Please contact your CSM for more details.
