### ISSUE TITLE
Autoplay on ios and android mobile browser dose't work 

### ISSUE THREAD

**Issue by Shailendra18** [kaltura/mwEmbed#2930]
mobile browser auto play support is given by kaltura or not

**Comment by kaltura-hooks** [comment]
Hi @Shailendra18,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by Shailendra18** [comment]
<script src="http://cdnapi.kaltura.com/p/2171861/sp/217186100/embedIframeJs/uiconf_id/35965662/partner_id/2171861"></script>
<script>
	var player_id;
      mw.setConfig( 'LeadWithHLSOnFlash' ,true);
      kWidget.embed({
         'targetId': 'kaltura_player_1470132100',
         'wid': '_2171861',
         'uiconf_id' : '35965662',
         'entry_id' : '1_w7kv2w81',
         'flashvars':{ 
              'autoPlay': "true",
			"userAgentPlayerRules":{ 
				'loadingPolicy':"onDemand",
				'disableForceMobileHTML5': "true", 
				'r1RegMatch': "/Chrome\/(1[5-9]|[1-9][0-9]+)/", 
				'r1LeadWithHTML5':"true",
				'r2Match': "Firefox/3.6", 
				'r2ForceFlash':"true", 
				'r3Match':"iPhone",
				'r3ForceMsg':"%3Ch3%3ESorry%3C/h3%3E%20Your%20device%20is%20%3Cb%3Enot%20supported%3Cb%3E", 
				'r4RegMatch':"/Firefox\/([4-9]|[0-9][0-9])/", 
				'r4LeadWithHTML5':"true"
			}

         },
         'params':{ 
              'wmode': 'transparent'
         },
         readyCallback: function( playerId ){
              console.log( 'Player:' + playerId + ' is ready '); 
         }
 });
</script>



This is the code i am using ... 
autoplay not working all mobile browsers ....

**Comment by peterrei** [comment]
I'm using Kaltura 11.7 and I tested all versions from 11.7 up to latest 11.20 and mobile autoplay is not supported.

Chrome will support this feature from version 53: https://developers.google.com/web/updates/2016/07/autoplay

Maybe in the future Kaltura also will support mobile autoplay with mute audio volume.

**Comment by jessp01** [comment]
Please see Amir's answer here:
https://forum.kaltura.org/t/kwidget-issue-with-mobile-devices-not-auto-playing/3388/2
Closing the issue.
