### ISSUE TITLE
Cuepoints not triggered instantly

### ISSUE THREAD

**Issue by prabjot678** [kaltura/mwEmbed#2952]
I am using kaltura dynamic embed player in my application, there user can set cue points to video. When i set any cue point on video,it is not reflected on player instantly. Sometimes, it takes 2 or 3 min to reflect. We are giving a preview functionality, so that's why i need it instantly.

**Add cuepoints on kaltura**

```
var cuePoint = new kaltura.kc.objects.KalturaAdCuePoint();
        cuePoint.entryId = entryId;
        cuePoint.startTime = startTime;
        cuePoint.title = title;
kalturaClient.cuePoint.add(function(results) {
                callback(results);
            });
```

**Events to listen cue points**

```
kWidget.embed({
        'targetId': 'embedPlayer',
        'wid': '',
        'uiconf_id' : '',
        'entry_id' : entry_id,
        'flashvars':{  
            'autoPlay': false,
        },
        height:height,
        width:width,
        'readyCallback': function( playerId ){
            console.log( "kWidget player ready: " + playerId );
            player = $( '#' + playerId ).get(0);
            player.kBind( "adOpportunity", "cuePointReached");
        }
    })

var cuePointReached = function(qPoint){
    console.log("cuePointReached " + qPoint)
}
```

I just want to know, is it a behaviour of kaltura or i am doing something wrong ?

Thanks in advance

**Comment by kaltura-hooks** [comment]
Hi @prabjot678,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by iddrew** [comment]
hi, 
was there ever any update to this please? We are also experiencing the same issue.

Kind Regards,
Andrew De Bono

**Comment by prabjot678** [comment]
@iddrew  Yes i have solved it by override cue points on run time, please find at
[](http://stackoverflow.com/questions/38995344/kaltura-cuepoints-not-triggered-instantly)

**Comment by OrenMe** [comment]
Hi @prabjot678, sorry you didn't het an answer, and glad you found a way to do it, which is correct per your requested feature, which is live preview.
The issue you mention is that you set cuepoints on the API which might take time to update due to caching so once you do add a cuepoint you won't see it immediately on the embedded player.
For your requested feature, to have a preview, you can indeed override the local cuepoints object as you did, and only when a user is satisfied with his preview result, you can then save it to the API, so it will take affect from then and onward.
