### ISSUE TITLE
Support "playsinline" in <video> for iOS Browsers

### ISSUE THREAD

**Issue by jjsee** [kaltura/mwEmbed#3118]
Currently, the EmbedPlayer.WebKitPlaysInline option when specified, injects "webkit-playsinline" into <video>player. 

As per the latest iOS 10 Safari changes, "webkit-playsinline" has been unprefixed into just "playsinline". Using "webkit-playsinline" no longer work for iOS browsers (tested on Safari and Chrome), but using "playsinline" would work (tested on Safari and Chrome). 

Are there any plan to support this new parameter soon? The impact is huge as this is affecting all iOS users that are on iOS 10. 

Sources:
https://webkit.org/blog/6784/new-video-policies-for-ios/
https://trac.webkit.org/changeset/202660

**Comment by kaltura-hooks** [comment]
Hi @jjsee,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Handled in latest version.
