### ISSUE TITLE
issues on iOS, logo just spins

### ISSUE THREAD

**Issue by jdeproost** [kaltura/mwEmbed#3157]
Hi,

Running Kalture CE 12.5.0-2 player
[example](http://146.185.182.10/index.php/extwidget/preview/partner_id/102/uiconf_id/23448344/embed/auto?&flashvars%5BstreamerType%5D=auto&flashvars%5BplaylistAPI.kpl0Id%5D=0_j36av2hk)
On iPhone and iPad the logo just spins.
Created a new universal player without changing any of the setting.
kWidget: Kaltura HTML5 Version: 2.50 should be iOS compatible or?

Any idea what I need to do to solve this?

Thanks in advance,
Johnny

`
dpkg -l "kaltura-*"
ii  kaltura-base           12.5.0-2         all              Kaltura Open Source Video Platform
ii  kaltura-batch          12.5.0-1         all              Kaltura Open Source Video Platform - batch server
ii  kaltura-clipapp        1.3-1+b2         all              Kaltura Video Presentations Manager
ii  kaltura-db             12.4.0-1+b1      all              Kaltura Open Source Video Platform - batch server
ii  kaltura-dwh            11.3.0-2+b3      amd64            Kaltura Open Source Video Platform - Analytics
ii  kaltura-ffmpeg         3.1.3-2+b2       amd64
ii  kaltura-ffmpeg-aux     2.1.3-1          amd64
ii  kaltura-front          12.5.0-1         all              Kaltura Open Source Video Platform - frontend ser
ii  kaltura-html5-studio   2.0.7-1          all              Kaltura Open Source Video Platform - frontend ser
ii  kaltura-html5lib       2.50-1+b1        all              Kaltura Open Source Video Platform - HTML5 player
ii  kaltura-kclip          1.1.2.1-1        all              Kaltura Video Presentations Manager
ii  kaltura-kcw            2.2.4-1+b3       all              Kalture Contribution Wizard
ii  kaltura-kdp            2.7.0-1          all              Kaltura Dynamic Player
ii  kaltura-kdp3           3.9.9-1+b3       amd64            Kaltura Dynamic Player
ii  kaltura-kdp3wrapper    37-1             all              KDP3 Wrapper
ii  kaltura-kdpwrapper     11-1             all              KDP Wrapper
ii  kaltura-kmc            5.40.3-5         all              Kaltura Management Console
ii  kaltura-krecord        1.7-1            all              Kaltura kRecord - used for recording from web cam
ii  kaltura-kupload        1.2.16-1         all              Kaltura kupload widget
un  kaltura-libapache2-mod <none>           <none>           (no description available)
ii  kaltura-nginx          1.10.2-1         amd64            Nginx web/proxy server - for Kaltura
ii  kaltura-pentaho        4.2.1+b2         amd64            Pentaho Open Source Data Integration Community Ed
un  kaltura-php7-apcu      <none>           <none>           (no description available)
un  kaltura-php7-cli       <none>           <none>           (no description available)
un  kaltura-php7-curl      <none>           <none>           (no description available)
un  kaltura-php7-gd        <none>           <none>           (no description available)
un  kaltura-php7-gmp       <none>           <none>           (no description available)
un  kaltura-php7-mcrypt    <none>           <none>           (no description available)
un  kaltura-php7-memcache  <none>           <none>           (no description available)
un  kaltura-php7-mysql     <none>           <none>           (no description available)
un  kaltura-php7-ssh2      <none>           <none>           (no description available)
un  kaltura-php7-xsl       <none>           <none>           (no description available)
ii  kaltura-postinst       1.0.31-1+b3      all              Kaltura Open Source Video Platform
ii  kaltura-red5           1.0.0-1+b2       amd64            Kaltura Open Source Video Platform
ii  kaltura-sphinx         2.2.1-4          amd64            Sphinx full-text search server - for Kaltura
ii  kaltura-widgets        10.9.0-1+b4      all              Kaltura Open Source Video Platform - widgets meta
`

**Comment by kaltura-hooks** [comment]
Hi @jdeproost,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Please test with latest player v2.60.2. Thanks.
