### ISSUE TITLE
360 doesn't work on iOS 10

### ISSUE THREAD

**Issue by slash851** [kaltura/mwEmbed#3352]
I am trying to play video 360 on iOS but it only shows the black screen.
I followed the instructions from the kalturas knowledge page:

https://knowledge.kaltura.com/kaltura-360-video-player-support

1. Ingest your asset as usual, via either the KMC or APIs. 
2. Tag the entry “360”.

here is the url to my video:
http://www.kaltura.com/index.php/extwidget/preview/partner_id/1822451/uiconf_id/39055441/entry_id/1_ovftzjab/embed/auto?&flashvars[streamerType]=auto&flashvars[video360.plugin]=true

**Comment by kaltura-hooks** [comment]
Hi @slash851,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by slash851** [comment]
Regarding to the additional informations:

**1.** Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?

Its only iPhone iOS 10 Safari issue, on desktop browsers it works ok

**2.** Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
If self hosted, are you using the RPM or deb install?

I use Kaltura account from kaltura.com/kmc website that is set up by your developers. Please see the url 
http://www.kaltura.com/index.php/extwidget/preview/partner_id/1822451/uiconf_id/39055441/entry_id/1_ovftzjab/embed/auto?&flashvars[streamerType]=auto&flashvars[video360.plugin]=true

**3.** Packages installed.

I dont have access to your servers so I am not able to do this operation.

**4.** When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

 no need for screenshots issue is replicable and it is happening every time you open 360 video on iPhone iOS device

**Comment by OrenMe** [comment]
Thanks @slash851.
360 is not supported on iOS due to webkit bug: https://bugs.webkit.org/show_bug.cgi?id=135379
