### ISSUE TITLE
Player doesnt play DoubleClick ad on Android Device when Thumbnail Embed is used.

### ISSUE THREAD

**Issue by slash851** [kaltura/mwEmbed#3484]
When using thumbnail Embed code player doesn't play Advertisement on Android device.

**Platform:**
- Android 6.0
- Chrome Browser

**URL:**
- http://jacekiagatka.byethost7.com/thumbAdvert.html

**Player version:**
- v2.58.3 (player created on kaltura.com/kmc account)

**Expected behavior:**
Press play on the thumbnail. Advertisement is loaded and play, after advertisement video is played .

**Actual behavior:**
After pressing play player shows for long time spinner. After some time of not Playing advertisement it plays video contend. (no ad displayed)

**Console log:**
kWidget: Kaltura HTML5 Version: 2.58.3
[Violation] Avoid using document.write().
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] 'setTimeout' handler took 447ms
[Violation] 'setTimeout' handler took 56ms
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] 'setTimeout' handler took 97ms
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
**Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.**

**Comment by kaltura-hooks** [comment]
Hi @slash851,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by slash851** [comment]
I have no access to the kaltura.com/kmc box to do # rpm -qa \"kaltura*\" and the rest of the asked things. 
I am embeding the player directly from cdnapi.kaltura.com


`

  | <script src="http://cdnapi.kaltura.com/p/1938601/sp/193860100/embedIframeJs/uiconf_id/40006501/partner_id/1938601"></script>
-- | --
  | <div id="kaltura_player_1501140567" style="width: 560px; height: 395px;" itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
  | <span itemprop="name" content="moneky_xvid"></span>
  | <span itemprop="description" content=""></span>
  | <span itemprop="duration" content="29"></span>
  | <span itemprop="thumbnail" content="http://cfvod.kaltura.com/p/1938601/sp/193860100/thumbnail/entry_id/1_pn5bo0a6/version/100000"></span>
  | <span itemprop="width" content="560"></span>
  | <span itemprop="height" content="395"></span>
  | <a href="http://corp.kaltura.com/products/video-platform-features">Video Platform</a>
  | <a href="http://corp.kaltura.com/Products/Features/Video-Management">Video Management</a>
  | <a href="http://corp.kaltura.com/Video-Solutions">Video Solutions</a>
  | <a href="http://corp.kaltura.com/Products/Features/Video-Player">Video Player</a></div>
  | <script>
  | kWidget.thumbEmbed({
  | "targetId": "kaltura_player_1501140567",
  | "wid": "_1938601",
  | "uiconf_id": 40006501,
  | "flashvars": {
  | "streamerType": "auto"
  | },
  | "cache_st": 1501140567,
  | "entry_id": "1_pn5bo0a6"
  | });
  | </script>

`

**Comment by OrenMe** [comment]
Hi @slash851, can you please check with branch 2.61-10-Sep

**Comment by itaykinnrot** [comment]
Closing
