### ISSUE TITLE
getCurrentTime() is not a function

### ISSUE THREAD

**Issue by rouvenherzog** [kaltura/mwEmbed#3494]
Hey,

I am running into a problem with Kaltura HTML5 Version: 2.59 with the youtube player, if an ad error is being thrown and the player is trying to restore itself.

When retrieving the player element time of `this.getPlayerElement()` (https://github.com/kaltura/mwEmbed/blob/a9f53742e4e0616fa98bdbebc7a5a0281065a6d0/modules/ExternalPlayers/resources/mw.EmbedPlayerYouTube.js#L672) it tries to access `getCurrentTime` of a video tag. This field is undefined and therefore throws:

    load.php?debug=false&lang=en&modules=mw.EmbedPlayerYouTube&pskwidgetpath=..%2Fkwidget-ps%2F&skin=no…:499 Uncaught TypeError:
    this.getPlayerElement(...).getCurrentTime is not a function
    at HTMLDivElement.getPlayerElementTime
    at HTMLDivElement.syncCurrentTime
    at HTMLDivElement.monitor [as parent_monitor]
    at HTMLDivElement.monitor
    at HTMLDivElement.startMonitor 
    at HTMLDivElement.restoreEventPropagation
    at mw.AdTimeline.restorePlayer
    at mw.DoubleClick.restorePlayer
    at mw.DoubleClick.onAdError 
    at Wo.<anonymous> 

**Update thanks to kaltura-hooks**

The issue is consistent across platforms if the following is triggered:
    
    this.adsLoader.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR, function(event) {
        _this.hideAdContainer(true);
        _this.onAdError(event);
    }, false);

I am using Kaltura SaaS, namely http://cdnapi.kaltura.com/html5/html5lib/v2.59/load.php.

**Comment by kaltura-hooks** [comment]
Hi @rouvenherzog,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by rouvenherzog** [comment]
Do you have any feedback on this?  @OrenMe  We are using the kaltura plugin in production and this issue causes the player to not paly the video sometimes. 😊

**Comment by OrenMe** [comment]
Hi @rouvenherzog, thanks for reporting.
While we are checking the issue, can you include a test page to show the issue?

**Comment by rouvenherzog** [comment]
@OrenMe Thank you for taking care of this!

Here is an example that does not work for me most of the times:
http://www.radio24.ch/events/mark-forster-131346703

I'm working on a windows 10 machine, using Version 60.0.3112.101 (Official Build) (64-bit) - though this issue is reported across devices and browsers.

**Comment by OrenMe** [comment]
@rouvenherzog thanks for the test page, really helped step things up.
Issue should be resolved in 2.61 branch, planned to be released on Sep. 13th.

**Comment by rouvenherzog** [comment]
@OrenMe Thank you very much for your support! I'm looking forward 👍

**Comment by OrenMe** [comment]
NP, closing this in the meanwhile. If you still see issues feel free to reopen.
