### ISSUE TITLE
Video 360 plugin doesnt work on Mac Safari and iOS 12

### ISSUE THREAD

**Issue by slash851** [kaltura/mwEmbed#3966]
Video 360 doesnt work on Safari browsers.

**Test URL:**
http://player.kaltura.com/modules/KalturaSupport/components/360/tests/360Test.html

**Test Browser:**
Mac Safari 12
iOS Safari 12

**Expected behavior**
Player convert 360 streached video to draggable video rendered on Canvas

**Actual behavior**
Player shows streached video on Html5 Video element

**Comment by kaltura-hooks** [comment]
Hi @slash851,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by slash851** [comment]
* Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
* Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?


Its not happening cross platform only iOS an Mac Safari
Its Kaltura website demo (not sure how is it hosted by Kaltura)

All tests were done on Kaltura demo pages therefor can not send the server details.

**Comment by OrenMe** [comment]
Hi @slash851, 360 and VR is supported by playkit and is supported also on iOS.
