### ISSUE TITLE
Bumper hanging on iPad

### ISSUE THREAD

**Issue by mksolemn** [kaltura/mwEmbed#4115]
How to test:
go to: http://player.kaltura.com/docs/index.php?path=kvast
open devTools and select iPad;

This will cause bumper to hang and player will remain in frozen state...

**Comment by shalommeoded** [comment]
@mksolemn Hi, thank you for reporting this.
However, kindly note that the VAST is deprecated, as we now use Google's doubleClick (IMA) library in order to play ads.

Additional about the Kaltura mwEmbed doubleClick plugin can be found in the following link:
http://player.kaltura.com/docs/DoubleClick

**Comment by mksolemn** [comment]
Pushed a fix for anyone interested:
https://github.com/mksolemn/mwEmbed/blob/Bumper-ipad-bug/modules/EmbedPlayer/resources/mw.MediaElement.js - line 279
`if( source.getFlavorId() && source.getFlavorId().toLowerCase() == 'iphonenew' || source.getFlavorId().toLowerCase() == 'ipadnew')`

Found missing condition... for ipad all flavor sources were getting set from desktop sources NOT mobile sources.

**Comment by mksolemn** [comment]
> @mksolemn Hi, thank you for reporting this.
> However, kindly note that the VAST is deprecated, as we now use Google's doubleClick (IMA) library in order to play ads.
> 
> Additional about the Kaltura mwEmbed doubleClick plugin can be found in the following link:
> http://player.kaltura.com/docs/DoubleClick

Bumper breaks regardless if it's VAST or DoubleClick

**Comment by kaltura-hooks** [comment]
Hi @mksolemn,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,
