### ISSUE TITLE
Invalid Set polyfill always overrides native browser Set

### ISSUE THREAD

**Issue by genadis** [kaltura/mwEmbed#4260]
The player bundles a Set polyfill which does not implement a valid Iterable, in addition it does not check if browser has already Set supported. It always overrides the native browser Set:

https://github.com/kaltura/mwEmbed/blob/master/modules/Hlsjs/resources/Polyfill_Set.js#L495

Since All the browsers today support Set natively, this Polyfill can be removed, or at least a test added and if browser already has support not apply the polyfill.

The above breaks using modern browser features such as:
`[...new Set()]`
will result in error of `TypeError: Set is not a function or its return value is not iterable`

**Comment by yairans** [comment]
Hi @genadis. we do check if the browser has already Set supported -https://github.com/kaltura/mwEmbed/blob/master/modules/Hlsjs/resources/Polyfill_Set.js#L15

**Comment by kaltura-hooks** [comment]
Hi @genadis,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by genadis** [comment]
Thank you for the quick response!

Below is code we execute in our kaltura player plugin (running in development):


![image](https://user-images.githubusercontent.com/6747147/157016612-4487fe3b-4bf7-4a3e-90d3-a0337dd149fc.png)

Doing a step into brings us into the polyfill constructor function:

![image](https://user-images.githubusercontent.com/6747147/157016719-7a7c8282-6d94-4f7c-83ee-6d4b58487cda.png)

Scrolling up the source code, this is the inclusion of the polyfill:

![image](https://user-images.githubusercontent.com/6747147/157017116-9896f91c-e057-4096-845a-d24ab73526ca.png)


I'm not sure how the polyfill is bundled, but it is included and applied in the final build, verified by debugging it as can be seen above.

* The issue is consistent
* using Chrome for debugging Version 98.0.4758.109 (Official Build) (x86_64).
* using kaltura SaaS (KMS). running locally (we are a Kaltura partner with KAF module + kaltura player plugin).
![image](https://user-images.githubusercontent.com/6747147/157018385-6509c9cf-0edc-4ce4-8134-b6eab571da0f.png)

**Comment by genadis** [comment]
@yairans I can see it's been fixed in this commit (Jun 2, 2021): https://github.com/kaltura/mwEmbed/commit/6f2479b7f663c6707fee6d6f2c546300c11dfa3c

I'll try to update the player version in KMC

**Comment by genadis** [comment]
@yairans updating the player, solved the issue.

thanks
